# Generated by Django 2.2.3 on 2021-01-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time'], 'verbose_name': '評論', 'verbose_name_plural': '評論'},
        ),
    ]
